### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by aleksslab** [htangsmart/FitCloudPro-SDK-Android#1]
I really need your help!
I want to understand the structure of the watch face file. Can you help me?

**Comment by Kilnn** [comment]
Sorry! The  watch face file compiling and decoding tool is basically provided by the Bluetooth manufacturer. I don't know the structure.

**Comment by aleksslab** [comment]
Hello. Your SDK have a function startCreateDial, that uses DialWriter. Do you have a source codes for this class?
P.S. Sorry for my poor english :)

**Comment by Circacadoo** [comment]
> I don't know the structure.

Can you please add a data export function to the app? Thanks!
