### ISSUE TITLE
dfuCallback onError errorType : 4  , errorCode: 275

### ISSUE THREAD

**Issue by hengbeishang** [htangsmart/FitCloudPro-SDK-Android#11]
dfuManager.upgradeDial(binPath, binFlag);
progress 99 %
dfuCallback onError errorType : 4 , errorCode: 275
What causes it?
就是说在市场进行表盘升级的时候，bin文件都下载完成了，在同步到手表99%的时候失败了，显示 errorType : 4 , errorCode: 275 ，想问一下是大概什么原因造成的？

**Comment by Kilnn** [comment]
缓冲区检查重试次数超过最大值。
重试一下吧。应该不是必现的吧？

**Comment by hengbeishang** [comment]
是必现的，试了差不多7、8个表盘都是这样，然后我根据你的SDK去我代码里面断点排查，愣是找不出那里不一样

**Comment by Kilnn** [comment]
我上传了libraryDfu_v1.0.7.aar的新版本，你下载试试

**Comment by hengbeishang** [comment]
哥们，解决了，是之前同事写的有问题
