### ISSUE TITLE
请问如何联系你们的商务？

### ISSUE THREAD

**Issue by sandy2008** [htangsmart/FitCloudPro-SDK-Android#2]
- 我们采购了1000个T68手环，希望能修改固件，比如字体。（我们的技术团队可以进行接洽，以进行开发。）
- 我们开发了React Native版本的FitCloudPro，同时支持iOS和Android，可以开源共享一起使用。
- 我们是一家日本的创业公司，诚意求合作。目前已经谈下众多日本的运动队，希望以后能进行长期合作。
- 我们的APP：
  - https://apps.apple.com/jp/app/id1515643297
  - https://play.google.com/store/apps/details?id=dev.wopal.fitness

**Comment by sandy2008** [comment]
希望可以传达我们的意向到你们的商务，谢谢！

**Comment by Kilnn** [comment]
加这个人的QQ：775900368
