### ISSUE TITLE
Suggest Changes - FitCloudPro

### ISSUE THREAD

**Issue by daygle** [htangsmart/FitCloudPro-SDK-Android#3]
Hi,

Are you the developer of FitCloudPro? I would like to suggest some changes.

I have attempted to contact via the in app to suggest improvement but it appears that I am not receiving a reply. Are you able to suggest a contact that I can forward suggestions/improvements?

Kind Regards
Glen

**Comment by Kelro-Lay** [comment]
需要有一个钱包功能，在地铁上掏出手机太麻烦了用钱包NFC付款这个功能更加实用

**Comment by Oxize** [comment]
Not all watches have NFC, Kelro. Atleast not mine, and manny others from AlieExpress.
