### ISSUE TITLE
How to edit a bin file watch face?

### ISSUE THREAD

**Issue by vtungabc** [htangsmart/FitCloudPro-SDK-Android#6]
I need a tool to edit bin files

**Comment by sumancbd** [comment]
Hi, it there a way to edit the .bin files? Or is there a way I can created a .bin file from scratch?

**Comment by Kilnn** [comment]
See the [Dial custom](https://github.com/htangsmart/FitCloudPro-SDK-Android/wiki/09.Dial#dial-custom)

**Comment by Kilnn** [comment]
> Hi, it there a way to edit the .bin files? Or is there a way I can create a .bin file from scratch?

See the [Dial Custom](https://github.com/htangsmart/FitCloudPro-SDK-Android/wiki/09.Dial#dial-custom)
