### ISSUE TITLE
Export collected data?

### ISSUE THREAD

**Issue by Circacadoo** [htangsmart/FitCloudPro-SDK-Android#9]
Hi, 

I would like to export the collected data as a csv for further analysis. 

Is this already possible. If so, how do I do that? 

Otherwise: Will the export feature be added to the app at one point? 

If not: What do I have to do to get you to add the data export feature?

Best regards & Thanks!

**Comment by MarianDV** [comment]
Is it possible to export ecg data?. .CSV would be ok

Thank you

**Comment by Circacadoo** [comment]
@MarianDV Watch out, the app is automatically deleting all data older than a month. It's truly the lousiest program I ever used.

**Comment by MarianDV** [comment]
> @MarianDV Watch out, the app is automatically deleting all data older than a month. It's truly the lousiest program I ever used.

Thanks @Circacadoo. Did you manage to export ecg/ppg data?

**Comment by MarianDV** [comment]
@Circacadoo thank you so much. You really saved me a lot of time!

**Comment by Kilnn** [comment]
What type of data do you want to export?

**Comment by MarianDV** [comment]
ECG, Accelerometer, plethysmography. Would it be possible?

Thank you!

**Comment by Kilnn** [comment]
There is no such data in the APP. These data may be stored in the watch, but they will not be transmitted to the APP.

**Comment by Kilnn** [comment]
I really don't have time to deal with this right now. 
The next version of FitCloudPro will write data to HealthConnect. Perhaps other applications have this function, which can read data from HealthConnect and export it.

**Comment by MarianDV** [comment]
Thank you. Could you please Export de whole ECG signal, not only Heart rate?. 

Regates, thanks for your time

**Comment by Kilnn** [comment]
> Thank you. Could you please Export de whole ECG signal, not only Heart rate?.
> 
> Regates, thanks for your time

Currently on the ECG report page, you can export pdf files. In the next version, I will add a long press share button to export txt files.

The next version may be more than 10 days later. We have 5 days vacation here, and then there are other features to be tested in the next version, which will also take some time.
